    scripts:
      - name: Reconstruct Android Project Structure
        script: |
          flutter create --platforms=android .
          # إعادة نسخ ملف خدمات جوجل إلى مجلد أندرويد المستحدث
          mkdir -p android/app
          cp google-services.json android/app/ 2>/dev/null || true
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
